name: flutter_finance_app
description: A new Flutter project.



publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: 
  percent_indicator: 
  google_fonts: 
  icon_badge: 
  pin_code_fields:
  local_auth:
  shared_preferences: 
  provider: 
  card_swiper: 
  flutter_staggered_grid_view:
  fancy_shimmer_image:
  google_sign_in:
  firebase_auth: 
  cloud_firestore: 
  firebase_storage: 
  firebase_core: 
  firebase_core_platform_interface:
  flutter_spinkit: 
  uuid: 
  fluttertoast:
  iconly: 
  dotted_border: 
  image_picker: 
  intl:
  calendar_date_picker2:
  flutter_datetime_picker_bdaya:
  phone_number: ^2.0.1
  intl_phone_field: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

 
  assets:
    - assets/ 
    - assets/images/
    - assets/images/landing/
 